### ISSUE TITLE
Incorrect formula for SE>1E60

### ISSUE THREAD

**Issue by carlneuhaus** [QuantumZizo/Egg-Inc-Calculator#1]
The formula for soul egg reward > 1e60 is missing the prestBonus term. Should be updated to
```
if(soulEggReward > 1E60) {
        soulEggReward = prestBonus * eventBoost * (10.0.pow(-6) * prestEarnings).pow(0.21) - 1.56 * 10.0.pow(11)
    }
```

**Comment by QuantumZizo** [comment]
Oh thanks for letting me know about that, shall be fixed soon. Also sorry for not responding until a while later as i’ve been a bit busy.

**Comment by QuantumZizo** [comment]
This has been fixed in the latest release, thank you for alerting me to the problem.
